spring:
  application:
    name: products
  profiles:
    default: dev
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health,info
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
inventory:
  base-url: ${INVENTORY_BASE_URL:http://localhost:8082}
  api-key:
    header: ${INVENTORY_API_KEY_HEADER:X-API-Key}
    value: ${INVENTORY_API_KEY_VALUE:dev-secret}
