spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: ${DB_USERNAME:appuser}
    password: ${DB_PASSWORD:apppass}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
security:
  api-key:
    enabled: ${API_KEY_ENABLED:true}
    header: ${API_KEY_HEADER:X-API-Key}
    value: ${API_KEY_VALUE:prod-secret}
